Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### Nginx VM ###
  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "ubuntu/xenial64"
    nginx.vm.hostname = "nginx"
	nginx.vm.network "private_network", ip: "192.168.33.11"
  end
  
### tomcat vm ###
   config.vm.define "tomcat" do |tomcat|
    tomcat.vm.box = "geerlingguy/centos7"
    tomcat.vm.hostname = "tomcat"
    tomcat.vm.network "private_network", ip: "192.168.33.12"
	tomcat.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
	 end
   end
   
### RabbitMQ vm  ####
  config.vm.define "rabbitmq" do |rabbitmq|
    rabbitmq.vm.box = "geerlingguy/centos7"
	rabbitmq.vm.hostname = "rabbitmq"
    rabbitmq.vm.network "private_network", ip: "192.168.33.16"
  end
  
### Memcache vm  #### 
  config.vm.define "memcashe" do |memcashe|
    memcashe.vm.box = "geerlingguy/centos7"
	memcashe.vm.hostname = "memcashe"
    memcashe.vm.network "private_network", ip: "192.168.33.14"
  end
  
### DB vm  ####
  config.vm.define "mysqldb" do |mysqldb|
    mysqldb.vm.box = "geerlingguy/centos7"
	mysqldb.vm.hostname = "mysqldb"
    mysqldb.vm.network "private_network", ip: "192.168.33.15"
  end
end
